### ISSUE TITLE
Error added the song to the playlist ("not added to playlist")

### ISSUE THREAD

**Issue by bl4zek** [MarcDonald/twitch-spotify-request-bot#24]
This problem:
![image](https://user-images.githubusercontent.com/48611299/173662848-73c6b04d-e8cd-4d4e-b909-18209f5dcbfc.png)

Put the link in .env SPOTIFY_PLAYLIST_ID the playlist and nothing

**Comment by bl4zek** [comment]
SPOTIFY_PLAYLIST_ID=https://open.spotify.com/playlist/abc123?si=749fjrn and abc123?si
But nothing

**Comment by MarcDonald** [comment]
Can you try without the `?si` part at the end? So just `SPOTIFY_PLAYLIST_ID=abc123`

**Comment by bl4zek** [comment]
SPOTIFY_PLAYLIST_ID='ah4jk3b7lu?' and nothing, the same this error

**Comment by MarcDonald** [comment]
Do any other playlists work?

**Comment by bl4zek** [comment]
Ready, I can solution my problem, I think that put incorrect the client ID and Secret ID
