### ISSUE TITLE
Q: Check if user is subscribed to channel?

### ISSUE THREAD

**Issue by Colorful98** [MarcDonald/twitch-spotify-request-bot#4]
Hey,

How hard would it be to implement the functionality that the bot only listens to subscribers in the chat?

**Comment by MarcDonald** [comment]
Hey sorry it took so long to get back to you on this, I had forgot to turn on notifications for this repo. Just added an extra option to limit the command to subscribers only. If you use the newest version (2.0.0) and update your config to include the new option (as shown in the example config) it should work for you.

**Comment by Colorful98** [comment]
Works flawlessly, thanks! 👍
